version: '3.8'
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1l8s6e2tl3sclz836ue9rpr709lusxte
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_DATABASE=IOM
      - MYSQL_USER=ruby
      - MYSQL_PASSWORD=F3OIMykQK8861xwSLdOw
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  api:
    build: ./Api
    environment:
      - NODE_ENV=production
      - PORT=3973
      - APP_IP=51.91.96.23
      - MYSQL_HOST=database
      - MYSQL_ROOT_PASSWORD=1l8s6e2tl3sclz836ue9rpr709lusxte
      - MYSQL_DATABASE=IOM
      - MYSQL_USER=ruby
      - MYSQL_PASSWORD=F3OIMykQK8861xwSLdOw
      - MYSQL_PORT=3306
    ports:
      - "3973:3973"
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
  app:
    build: ./icionmine
    environment:
      - REACT_APP_BASE_URL=localhost
      - REACT_APP_PORT=3973
    ports:
        - "3000:3000"
    links:
      - api
