-- MySQL Script generated by MySQL Workbench
-- Sat Jan  7 13:29:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IOM
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `IOM` ;

-- -----------------------------------------------------
-- Schema IOM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IOM` ;
USE `IOM` ;

-- -----------------------------------------------------
-- Table `IOM`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`USER` ;

CREATE TABLE IF NOT EXISTS `IOM`.`USER` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARBINARY(255) NOT NULL,
  `activityMessage` VARCHAR(120) NULL,
  `isConnected` TINYINT NOT NULL DEFAULT 0,
  `isBlackListed` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `IOM`.`USER_LOGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`USER_LOGO` ;

CREATE TABLE IF NOT EXISTS `IOM`.`USER_LOGO` (
  `path` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `seed` INT NOT NULL,
  `sizeMo` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`, `userUuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_LOGO_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_LOGO_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `IOM`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`USER_IP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`USER_IP` ;

CREATE TABLE IF NOT EXISTS `IOM`.`USER_IP` (
  `ip` VARCHAR(16) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`, `userUuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_IP_1_idx` (`userUuid` ASC) VISIBLE,
  UNIQUE INDEX `ip_UNIQUE` (`ip` ASC) VISIBLE,
  CONSTRAINT `fk_USER_IP_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `IOM`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`USER_MAC_ADDRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`USER_MAC_ADDRESS` ;

CREATE TABLE IF NOT EXISTS `IOM`.`USER_MAC_ADDRESS` (
  `macAddress` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`, `userUuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_MACADDRESS_1_idx` (`userUuid` ASC) VISIBLE,
  UNIQUE INDEX `macAddress_UNIQUE` (`macAddress` ASC) VISIBLE,
  CONSTRAINT `fk_USER_MACADDRESS_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `IOM`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`USER_DEVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`USER_DEVICE` ;

CREATE TABLE IF NOT EXISTS `IOM`.`USER_DEVICE` (
  `device` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`, `userUuid`),
  INDEX `fk_USER_DEVICE_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_DEVICE_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `IOM`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`USER_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`USER_HISTORY` ;

CREATE TABLE IF NOT EXISTS `IOM`.`USER_HISTORY` (
  `log` TEXT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`, `userUuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_HISTORY_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_HISTORY_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `IOM`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`USER_TOKEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`USER_TOKEN` ;

CREATE TABLE IF NOT EXISTS `IOM`.`USER_TOKEN` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expireAt` DATETIME NOT NULL,
  `salt` VARBINARY(128) NOT NULL,
  `token` TEXT NOT NULL,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`, `userUuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_TOKEN_1_idx` (`userUuid` ASC) VISIBLE,
  UNIQUE INDEX `userUuid_UNIQUE` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_TOKEN_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `IOM`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`ROLE` ;

CREATE TABLE IF NOT EXISTS `IOM`.`ROLE` (
  `name` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`USER_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`USER_ROLE` ;

CREATE TABLE IF NOT EXISTS `IOM`.`USER_ROLE` (
  `roleId` INT NOT NULL,
  `userUuid` BINARY(16) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `userUuid`, `roleId`),
  INDEX `fk_USER_ROLE_1_idx` (`userUuid` ASC) VISIBLE,
  INDEX `fk_USER_ROLE_2_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `fk_USER_ROLE_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `IOM`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_ROLE_2`
    FOREIGN KEY (`roleId`)
    REFERENCES `IOM`.`ROLE` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`MODULE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`MODULE` ;

CREATE TABLE IF NOT EXISTS `IOM`.`MODULE` (
  `moduleName` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`ROLE_MODULE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`ROLE_MODULE` ;

CREATE TABLE IF NOT EXISTS `IOM`.`ROLE_MODULE` (
  `roleId` INT NOT NULL,
  `moduleId` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`, `roleId`, `moduleId`),
  INDEX `fk_ROLE_MODULE_1_idx` (`roleId` ASC) VISIBLE,
  INDEX `fk_ROLE_MODULE_2_idx` (`moduleId` ASC) VISIBLE,
  CONSTRAINT `fk_ROLE_MODULE_1`
    FOREIGN KEY (`roleId`)
    REFERENCES `IOM`.`ROLE` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROLE_MODULE_2`
    FOREIGN KEY (`moduleId`)
    REFERENCES `IOM`.`MODULE` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`ARTICLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`ARTICLE` ;

CREATE TABLE IF NOT EXISTS `IOM`.`ARTICLE` (
  `title` TEXT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `content` LONGTEXT NOT NULL,
  `pubDate` DATE NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`CATEGORY_FLUX_RSS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`CATEGORY_FLUX_RSS` ;

CREATE TABLE IF NOT EXISTS `IOM`.`CATEGORY_FLUX_RSS` (
  `name` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`SOURCE_FLUX_RSS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`SOURCE_FLUX_RSS` ;

CREATE TABLE IF NOT EXISTS `IOM`.`SOURCE_FLUX_RSS` (
  `url` VARCHAR(255) NOT NULL,
  `categoryId` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `url_UNIQUE` (`url` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_SOURCE_FLUX_RSS_1`
    FOREIGN KEY (`id`)
    REFERENCES `IOM`.`CATEGORY_FLUX_RSS` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`ARTICLE_HAS_CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`ARTICLE_HAS_CATEGORY` ;

CREATE TABLE IF NOT EXISTS `IOM`.`ARTICLE_HAS_CATEGORY` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `categoryId` INT NOT NULL,
  `articleId` INT NOT NULL,
  PRIMARY KEY (`id`, `categoryId`, `articleId`),
  INDEX `fk_ARTICLE_HAS_CATEGORY1_idx` (`articleId` ASC) VISIBLE,
  INDEX `fk_ARTICLE_HAS_CATEGORY2_idx` (`categoryId` ASC) VISIBLE,
  CONSTRAINT `fk_ARTICLE_HAS_CATEGORY1`
    FOREIGN KEY (`articleId`)
    REFERENCES `IOM`.`ARTICLE` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ARTICLE_HAS_CATEGORY2`
    FOREIGN KEY (`categoryId`)
    REFERENCES `IOM`.`CATEGORY_FLUX_RSS` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IOM`.`PREFERENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `IOM`.`PREFERENCE` ;

CREATE TABLE IF NOT EXISTS `IOM`.`PREFERENCE` (
  `id` VARCHAR(255) NOT NULL,
  `symbol` VARCHAR(255) NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
