-- MySQL Script generated by MySQL Workbench
-- mar. 22 nov. 2022 14:24:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TheCountOfMoney
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TheCountOfMoney` ;

-- -----------------------------------------------------
-- Schema TheCountOfMoney
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TheCountOfMoney` ;
USE `TheCountOfMoney` ;

-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARBINARY(255) NOT NULL,
  `activityMessage` VARCHAR(120) NULL,
  `isConnected` TINYINT NOT NULL DEFAULT 0,
  `isBlackListed` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_LOGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_LOGO` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_LOGO` (
  `path` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `seed` INT NOT NULL,
  `sizeMo` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_LOGO_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_LOGO_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_IP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_IP` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_IP` (
  `ip` VARCHAR(16) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_IP_1_idx` (`userUuid` ASC) VISIBLE,
  UNIQUE INDEX `ip_UNIQUE` (`ip` ASC) VISIBLE,
  CONSTRAINT `fk_USER_IP_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_MAC_ADDRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_MAC_ADDRESS` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_MAC_ADDRESS` (
  `macAddress` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_MACADDRESS_1_idx` (`userUuid` ASC) VISIBLE,
  UNIQUE INDEX `macAddress_UNIQUE` (`macAddress` ASC) VISIBLE,
  CONSTRAINT `fk_USER_MACADDRESS_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_DEVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_DEVICE` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_DEVICE` (
  `device` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  INDEX `fk_USER_DEVICE_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_DEVICE_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_FRIEND`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_FRIEND` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_FRIEND` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `acceptedAt` DATETIME NULL,
  `isAccepted` TINYINT NOT NULL DEFAULT 0,
  `user` BINARY(16) NOT NULL,
  `friend` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  INDEX `fk_USER_FRIEND_1_idx` (`user` ASC) VISIBLE,
  INDEX `fk_USER_FRIEND_2_idx` (`friend` ASC) VISIBLE,
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_FRIEND_1`
    FOREIGN KEY (`user`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_FRIEND_2`
    FOREIGN KEY (`friend`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_HISTORY` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_HISTORY` (
  `log` TEXT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_HISTORY_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_HISTORY_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_REPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_REPORT` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_REPORT` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reason` TEXT NOT NULL,
  `userSendReport` BINARY(16) NOT NULL,
  `userReported` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_REPORT_1_idx` (`userSendReport` ASC) VISIBLE,
  INDEX `fk_USER_REPORT_2_idx` (`userReported` ASC) VISIBLE,
  CONSTRAINT `fk_USER_REPORT_1`
    FOREIGN KEY (`userSendReport`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_REPORT_2`
    FOREIGN KEY (`userReported`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_TOKEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_TOKEN` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_TOKEN` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expireAt` DATETIME NOT NULL,
  `salt` VARBINARY(128) NOT NULL,
  `token` TEXT NOT NULL,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_TOKEN_1_idx` (`userUuid` ASC) VISIBLE,
  UNIQUE INDEX `userUuid_UNIQUE` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_TOKEN_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`ROLE` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`ROLE` (
  `name` VARCHAR(45) NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_ROLE` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_ROLE` (
  `roleId` INT NOT NULL,
  `userUuid` BINARY(16) NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `fk_USER_ROLE_1_idx` (`userUuid` ASC) VISIBLE,
  INDEX `fk_USER_ROLE_2_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `fk_USER_ROLE_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_ROLE_2`
    FOREIGN KEY (`roleId`)
    REFERENCES `TheCountOfMoney`.`ROLE` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`MODULE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`MODULE` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`MODULE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `moduleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`ROLE_MODULE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`ROLE_MODULE` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`ROLE_MODULE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `roleId` INT NOT NULL,
  `moduleId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ROLE_MODULE_1_idx` (`roleId` ASC) VISIBLE,
  INDEX `fk_ROLE_MODULE_2_idx` (`moduleId` ASC) VISIBLE,
  CONSTRAINT `fk_ROLE_MODULE_1`
    FOREIGN KEY (`roleId`)
    REFERENCES `TheCountOfMoney`.`ROLE` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROLE_MODULE_2`
    FOREIGN KEY (`moduleId`)
    REFERENCES `TheCountOfMoney`.`MODULE` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheCountOfMoney`.`USER_DOCUMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TheCountOfMoney`.`USER_DOCUMENTS` ;

CREATE TABLE IF NOT EXISTS `TheCountOfMoney`.`USER_DOCUMENTS` (
  `path` VARCHAR(255) NOT NULL,
  `seed` INT NOT NULL,
  `sizeMo` INT NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_DOCUMENTS_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_DOCUMENTS_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `TheCountOfMoney`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
