CREATE TABLE IF NOT EXISTS `IOM`.`CATEGORY_FLUX_RSS`
(
    `name` VARCHAR(45) NOT NULL,
    `id`   INT         NOT NULL AUTO_INCREMENT,
    UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
    PRIMARY KEY (`id`)
)
    ENGINE = InnoDB;
